"""The report tables: detection at two thresholds, and scorer agreement.

Two detection tables -- one per scorer family, the shipped rule in both -- and
the Phase 2c agreement matrices. Every number comes from
:func:`injection_test.cell_statistics`, so the tables and the sweep's text
summary cannot disagree; a second implementation of the same statistic is what
let a wrong estimator look verified.

Bars are DERIVED from the scored population at run time, never hardcoded.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

from fis import paths
from fis.analysis import baseline, heldout, injection_test

#: Both tables carry the shipped rule and its ungated twin, so the gate's cost
#: is readable in each without cross-referencing the other.
SHARED = ("max", "max_ungated")
#: Both forest readings appear: the raw isolation score and the score
#: normalised against its own fit's training rows. They rank the same fit but
#: not identically, and the normalised one is the only form comparable across
#: players whose fits borrowed different amounts.
DIRECT = SHARED + ("mahalanobis", "forest", "forest_norm")
RESIDUAL = SHARED + ("mahalanobis_z", "forest_res", "forest_res_norm")

#: Every unique rule, in table order -- what the agreement matrices span.
EVERY_TALLY = DIRECT + tuple(s for s in RESIDUAL if s not in DIRECT)

#: 1% is what ships; 5% is above the gate's ceiling and asterisks itself.
RATES = (0.01, 0.05)

#: Below this, one player moves a cell by ten points or more, so the grid
#: measures its own sample rather than the scorers. Such cuts report a count
#: instead -- GK is thin enough that it will normally be one of them.
MIN_MATRIX_PLAYERS = 10


def _fold(title: str, body: str) -> str:
    """A GitHub-collapsible section; blank lines let markdown render inside."""
    return f"\n<details>\n<summary><b>{title}</b></summary>\n{body}\n\n</details>"


def _context(scored: pd.DataFrame, rates: tuple[float, ...], headline) -> str:
    """Three sentences of provenance, so the first grid is not the first thing
    a reader arriving from the README sees."""
    from datetime import date

    mechanism, severity = headline
    return "\n".join(
        [
            f"Generated by `fis-report` on {date.today().isoformat()}, from the "
            "leave-one-out census and the sigma-calibrated injection harness.",
            f"Population: {len(scored):,} scoreable player-matches / "
            f"{scored['player_id'].nunique():,} players; every number below is "
            "derived from this run at render time, never hardcoded.",
            f"Config: severity ladder k = {injection_test.SEVERITIES}, detection "
            "bars at "
            + " and ".join(f"{r:.0%}" for r in sorted(rates))
            + f" flag rates, agreement matrices keyed on `{mechanism}:{severity:g}`. "
            "Tables re-render from the saved results parquet without re-running "
            "the analysis.",
        ]
    )


def headline_summary(stats: pd.DataFrame, low: float, headline) -> str:
    """The result the tables exist to support, derived from THIS run's cells.

    Hardcoding it would be the delivered-rate mistake again: a summary that
    reads as measured while quietly describing an earlier population."""
    mechanism, severity = headline
    single = "pass_completion"

    def pick(tally: str, mech: str):
        row = stats[
            (stats.tally == tally) & (stats.mechanism == mech) & (stats.severity == severity)
        ]
        return row.iloc[0] if len(row) and np.isfinite(row.iloc[0].recovery) else None

    table = [
        f"| | single metric (`{single}`) | coordinated (all four) |",
        "|---|---:|---:|",
    ]
    for tally, label in (
        ("max", "max\\|z\\| (shipped, gated)"),
        ("mahalanobis_z", "mahalanobis_z"),
        ("forest", "forest"),
        ("forest_res", "forest_res"),
    ):
        a, b = pick(tally, single), pick(tally, mechanism)
        if a is None and b is None:
            continue

        def cell(r) -> str:
            return f"{r.recovery:.1%} ±{r.recovery_se:.1%}" if r is not None else "n/a"

        table.append(f"| {label} | {cell(a)} | {cell(b)} |")
    tail = (
        "The forests are the weakest scorers against a single-metric "
        "manipulation and the strongest against the coordinated one."
    )
    forest, shipped = pick("forest", mechanism), pick("max", mechanism)
    if forest is not None and shipped is not None and shipped.recovery:
        tail += (
            f" On the coordinated injection the forest recovers "
            f"**{forest.recovery / shipped.recovery:.1f}× the shipped rule**."
        )
    return "\n".join(
        [
            "\n## Headline\n",
            "**The scorer ordering flips between conditions** — recovery at the "
            f"shipped {low:.0%} bar, k={severity:g}:",
            "",
            *table,
            "",
            tail,
        ]
    )


def _pct(value: float, width: int = 5) -> str:
    return "n/a".rjust(width) if not np.isfinite(value) else f"{value:{width}.1%}"


def detection_table(
    per_rate: dict[float, pd.DataFrame], tallies: tuple[str, ...], title: str
) -> str:
    """One family's cells at both thresholds.

    AUC, achieved dose and clipped share are threshold-FREE, so they appear
    once. Printing them per rate would imply a dependence that does not exist
    and invite reading two identical columns as agreement between thresholds.
    """
    low, high = min(per_rate), max(per_rate)
    base = per_rate[low]
    lines = [
        f"| scorer | injection | k | delivered | n | dosed | auc | clipped "
        f"| recovery @{low:.0%} | recovery @{high:.0%} | collateral |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for tally in tallies:
        rows = base[base.tally == tally]
        if rows.empty:
            continue
        for first, row in enumerate(rows.itertuples()):
            other = per_rate[high]
            match = other[
                (other.tally == tally)
                & (other.mechanism == row.mechanism)
                & (other.severity == row.severity)
            ]
            hi = match.iloc[0] if len(match) else None
            collateral = f"{row.shift:+.4f}" if row.collateral_measurable else "not measured"

            def rate(cell) -> str:
                """Attempted-target rate, then the same numerator over the rows
                the injection actually moved, then in brackets how many rows
                could not reach the k this row is labelled with."""
                out = f"{_pct(cell.recovery)} ±{_pct(cell.recovery_se, 4)}"
                if np.isfinite(cell.recovery_dosed):
                    # Its interval matters MORE than the attempted rate's: the
                    # denominator is smaller, so it is the noisier of the two.
                    # Bare, it would read as the firmer measurement.
                    out += f" → {_pct(cell.recovery_dosed)} ±{_pct(cell.recovery_dosed_se, 4)}"
                if getattr(cell, "n_short", 0):
                    out += f" [{int(cell.n_short):,} short]"
                return out

            high_cell = rate(hi) if hi is not None else "n/a"
            dosed_n = f"{int(row.n_dosed):,}" if row.n_dosed else "n/a"
            delivered = f"{row.achieved:+.2f} sd" if np.isfinite(row.achieved) else "per-DOF"
            lines.append(
                f"| {f'**{tally}**' if not first else ''} | {row.mechanism} "
                f"| {row.severity:.3g} | {delivered} | {row.n:,} | {dosed_n} "
                f"| {f'{row.auc:.3f}' if np.isfinite(row.auc) else 'n/a'} "
                f"| {_pct(row.clipped, 4)} "
                f"| {rate(row)} "
                f"| {high_cell} | {collateral} |"
            )
    return "\n".join(lines)


def _matrix(labels: list[str], cell) -> str:
    """Square markdown table of ``cell(a, b)``, row label first."""
    rows = [
        "| | " + " | ".join(labels) + " |",
        "|---|" + "---:|" * len(labels),
    ]
    for a in labels:
        rows.append(f"| **{a}** | " + " | ".join(cell(a, b) for b in labels) + " |")
    return "\n".join(rows)


def target_agreement(scored: pd.DataFrame, census: pd.DataFrame, scorers: tuple[str, ...]) -> str:
    """Share of players for whom two scorers chose the SAME match.

    Independent of mechanism, severity AND bar: every column medianed on is a
    clean census column, so this is one matrix rather than one per condition.
    Players a scorer could not score are excluded from its pairs and reported
    as coverage instead -- they inherit the shipped rule's row, and counting
    that as agreement would flatter exactly the scorers with the least to say.
    """
    default, choices = injection_test.target_choices(scored, census, scorers)
    everyone = set(default)
    present = [s for s in scorers if s in choices]
    position = census.groupby("player_id")["position_code"].first()

    def block(players: set, title: str, folded: bool = False) -> str:
        def cell(a: str, b: str) -> str:
            both = set(choices[a]) & set(choices[b]) & players
            if not both:
                return "n/a"
            same = sum(1 for p in both if choices[a][p] == choices[b][p])
            return f"{same / len(both):.0%} ({len(both)})"

        cover = (
            ", ".join(f"{s} {len(set(choices[s]) & players) / len(players):.0%}" for s in present)
            if players
            else ""
        )
        if folded:
            return (
                f"\n<details>\n<summary>{title} (n={len(players):,})</summary>\n"
                f"\n{_matrix(present, cell)}\n\ncoverage: {cover}\n\n</details>"
            )
        return (
            f"\n### {title} (n={len(players):,})\n\n{_matrix(present, cell)}\n\ncoverage: {cover}"
        )

    out = [
        "\nBar- and dose-free. Gated and ungated max|z| rank on the same statistic, so they",
        "would share every target by construction and are not listed twice. Cells exclude",
        "players a scorer could not score; those appear in `coverage` instead.",
        block(everyone, "all positions"),
    ]
    for code in heldout.POSITIONS:
        cut = {p for p in everyone if position.get(p) == code}
        if not cut:
            continue
        if len(cut) < MIN_MATRIX_PLAYERS:
            out.append(
                f"\n*position {code}: {len(cut)} players — too few to compare; "
                "a grid this thin measures the sample, not the scorers.*"
            )
            continue
        out.append(block(cut, f"position {code}", folded=True))
    return "\n".join(out)


def detection_agreement(
    results: pd.DataFrame,
    bars: dict[str, float],
    mechanism: str,
    severity: float,
    tallies: tuple[str, ...],
    rate: float,
    sigma_gate: float = baseline.CORROBORATING_SIGMA,
) -> str:
    """Share of flagged PLAYERS two scorers share, at one dose and one bar.

    Counted per player, not per row: two scorers perturb different matches, so
    a row-level comparison would score them as disagreeing whenever their
    target choices differ, which Matrix 1 already measures separately.
    """
    block = results[
        (results.mechanism == mechanism) & (results.severity == severity) & results.is_target
    ]
    position = block.groupby("player_id")["position_code"].first()
    caught: dict[str, set] = {}
    for tally, scorer, gated in injection_test.tallies_for(set(block["scorer"]), bars):
        if tally not in tallies:
            continue
        r = block[block.scorer == scorer]
        hit = r["after"] >= bars[tally]
        if scorer == "max" and gated:
            hit = hit & (r["sigma_after"].abs() >= sigma_gate)
        caught[tally] = set(r.loc[hit, "player_id"])
    present = [t for t in tallies if t in caught]

    def block_for(players: set, title: str, folded: bool = False) -> str:
        sets = {t: caught[t] & players for t in present}

        def cell(a: str, b: str) -> str:
            caught_a, caught_b = sets[a], sets[b]
            union = len(caught_a | caught_b)
            if not union:
                return "n/a"
            shared = len(caught_a & caught_b)
            # A caught nothing, so "of A's catches" has no denominator -- the
            # Jaccard still does, and 0% there is a real statement about B.
            row = f"{shared / len(caught_a):.0%}" if caught_a else "-"
            return f"{row}/{shared / union:.0%}"

        sizes = ", ".join(f"{t} {len(sets[t])}" for t in present)
        if folded:
            return (
                f"\n<details>\n<summary>{title} (n={len(players):,})</summary>\n"
                f"\n{_matrix(present, cell)}\n\ncaught: {sizes}\n\n</details>"
            )
        return f"\n### {title} (n={len(players):,})\n\n{_matrix(present, cell)}\n\ncaught: {sizes}"

    everyone = set(block["player_id"])
    out = [
        "\nCell = `|A∩B|/|A|` / Jaccard. Row A, column B: of the players A caught, the share",
        "B also caught. Asymmetric on purpose — a scorer that catches few reads high across",
        "its row and low down its column.",
        block_for(everyone, "all positions"),
    ]
    for code in heldout.POSITIONS:
        cut = {p for p in everyone if position.get(p) == code}
        if not cut:
            continue
        # The denominator here is what a scorer CAUGHT, not the cut's size: a
        # position with plenty of players but few catches still cannot support
        # percentages.
        largest = max((len(caught[t] & cut) for t in present), default=0)
        if largest < MIN_MATRIX_PLAYERS:
            out.append(
                f"\n*position {code}: {len(cut)} players, most caught by any scorer "
                f"{largest} — too few to compare.*"
            )
            continue
        out.append(block_for(cut, f"position {code}", folded=True))
    return "\n".join(out)


def build(
    scored: pd.DataFrame,
    census: pd.DataFrame,
    results: pd.DataFrame,
    headline: tuple[str, float],
    rates: tuple[float, ...] = RATES,
) -> str:
    """Every table, from one results frame."""
    reference = injection_test.reference_scores(scored, census)
    bars = {r: heldout.production_bars(scored, census, r) for r in rates}
    per_rate = {
        r: injection_test.cell_statistics(results, bars[r], reference=reference) for r in rates
    }
    # "max" is merged in from the scored frame, not a census column, so it must
    # be admitted explicitly or the shipped rule drops out of the matrix. A
    # forest-free census still CARRIES the forest columns, all-NaN, so presence
    # is not enough -- they would fill the matrix with dead rows at 0% coverage.
    scorers = tuple(
        s
        for s in injection_test.SCORERS + injection_test.FOREST_SCORERS
        if s == "max" or (s in census and census[s].notna().any())
    )
    mechanism, severity = headline
    parts = [
        "# Phase 2 — injection sensitivity\n",
        _context(scored, rates, headline),
        headline_summary(per_rate[min(rates)], min(rates), headline),
        "\n```",
        injection_test.census_rates(scored, census, bars[min(rates)], min(rates)),
        "```",
        _fold("DIRECT metric space", detection_table(per_rate, DIRECT, "DIRECT metric space")),
        _fold("RESIDUAL (z) space", detection_table(per_rate, RESIDUAL, "RESIDUAL (z) space")),
        _fold(
            "Target agreement (same match chosen)",
            target_agreement(scored, census, scorers),
        ),
    ]
    # Matrix 2 at the SHIPPED rate only. The 5% pass was a control on whether
    # agreement is a bar artefact; the caught counts printed under each grid
    # carry that, and the census is cached, so it can be added later without
    # refitting anything.
    shipped = min(rates)
    parts.append(
        _fold(
            f"Detection agreement ({mechanism}, k={severity:g}, bar {shipped:.0%})",
            detection_agreement(results, bars[shipped], mechanism, severity, EVERY_TALLY, shipped),
        )
    )
    parts.append(_fold("Notes", caption(scored, census, rates)))
    return "\n".join(parts)


def _shrinkage_note(scored: pd.DataFrame) -> str:
    """The covariance shrinkage actually in force, per position."""
    nus = heldout.position_nus(scored)
    if not nus:
        return "- Covariance shrinkage: no position pool large enough to estimate."
    detail = ", ".join(f"{p} {v:.2f}" for p, v in nus.items())
    return (
        f"- **Covariance shrinkage** `nu` {min(nus.values()):.2f}–{max(nus.values()):.2f} "
        f"({detail}), the matches of evidence each position's covariance is worth. "
        "A player's own covariance carries weight n/(n+nu), so it takes over as his "
        "history lengthens rather than at a match-count threshold."
    )


def caption(scored: pd.DataFrame, census: pd.DataFrame, rates: tuple[float, ...]) -> str:
    """What a reader needs to not over-read the tables."""
    return "\n".join(
        [
            f"\n- Population {len(scored):,} rows / {scored['player_id'].nunique():,} players. "
            "**Observed, not certified-clean**, so base rates are upper bounds on FPR.",
            # The evaluated cut is a dbt var, not a Python constant, so it is read
            # off the frame -- writing 30 into the string would misstate the
            # population the moment the mart is rebuilt with a different value.
            f"- Eligibility: ≥{baseline.BASELINE_MIN_MINUTES:g} min baselines, "
            f"≥{scored['minutes_played'].min():g} min evaluated "
            f"(the mart's cut, read off this frame), "
            f"≥{baseline.MIN_PLAYER_MATCHES:g} appearances.",
            # Derived, not quoted: the range is a measurement of one population and
            # would go quietly wrong the moment the mart moves. Costs ~0.3s.
            _shrinkage_note(scored),
            "- **Two denominators.** `recovery` is over ALL attempted targets; the figure after "
            "`→` is the same numerator over `dosed` — rows the injection actually moved. A "
            "requested dose that rounds below one event is a real draw from the treatment and "
            "stays in the first; conditioning only on non-zero draws would select on the "
            "randomisation. **On the coordinated row it reads n/a**: 'some channel moved' is "
            "true on nearly every row and would imply a correction that was not made — there "
            "the per-channel `acted` shares carry it instead.",
            "- **Recovery** is crossing the bar *because of* the injection (below when clean, "
            "above after). It is not the same as caught, which counts rows already flagged "
            "before anything was injected. `±` is an Agresti-Coull SE, which does not collapse "
            "to zero on an empty cell — a 0.0% recovery means no events were seen, not that the "
            "rate was measured to be zero. At k=0 the zero IS exact and its SE is 0.",
            "- **AUC is threshold-free**, so it is reported once rather than per rate. Its "
            "no-skill line is the **k=0 row, not 0.5** — median-selected targets fire the sigma "
            "gate far less often than the population does.",
            "- **Do not compare mechanism rows as if they were equally injected.** `delivered` "
            "is the dose that actually landed, and it varies by mechanism: `pass_completion` "
            "delivers essentially all of what is asked and clips on no rows, while "
            "`remove_defensive` clips on most rows and lands under half. A mechanism that looks "
            "harder to detect may simply have been injected more weakly.",
            "- **Clipped** is the share of injected targets whose dose was TRUNCATED — the "
            "mechanism ran out of successes to relabel, or actions to remove, or touches to "
            "relocate. Those rows received *less* than was asked for, so a miss there is "
            "delivery rather than detection. Read it beside the achieved dose, which says how "
            "much was actually delivered on average.",
            "- Detection agreement is **one condition and the shipped 1% bar only**. Agreement rises with "
            "set size alone, so read the `caught` counts under each grid before reading the "
            "percentages. Note that k is split across channels on the coordinated condition "
            "(`compose` divides by √parts), so `correlated:3.0` delivers 1.5 sd per channel — "
            "the middle of the ladder per channel, not the extreme the label suggests.",
            f"- Position grids resting on fewer than {MIN_MATRIX_PLAYERS} players report a "
            "count instead of percentages. Below that, one player moves a cell by ten points.",
            "- Bars are derived from this population at run time, never hardcoded.",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="fis-report", description=__doc__.splitlines()[0])
    parser.add_argument(
        "--n",
        type=int,
        default=None,
        help="cap the players SCORED. Hyperparameters and residuals are still "
        "derived from the whole mart per condition, which is deliberate but "
        "means a small --n speeds this up far less than it looks.",
    )
    parser.add_argument(
        "--results",
        type=str,
        default=None,
        help="parquet holding the injection results. If it exists, the analysis "
        "is SKIPPED and the report re-renders from it, so a caption or "
        "column change costs seconds rather than a whole campaign. Written "
        "on every run and fingerprint-guarded, so results computed under a "
        "different estimator are refused rather than silently rendered.",
    )
    parser.add_argument(
        "--census",
        type=str,
        default=None,
        help="parquet to cache the census in. With forests it dominates the "
        "runtime, and it is fingerprint-guarded, so re-rendering a table "
        "costs nothing rather than refitting every row.",
    )
    parser.add_argument("--jobs", type=int, default=-1)
    parser.add_argument("--seed", type=int, default=injection_test.SEED)
    parser.add_argument("--forest", action="store_true", help="fit forests (dominates the runtime)")
    parser.add_argument(
        "--headline",
        default="correlated:3.0",
        help="mechanism:severity keying the agreement matrices. The coordinated "
        "case by default: it is what a manipulator most resembles, and "
        "compose() divides k by sqrt(parts), so correlated:3.0 is 1.5 sd per "
        "CHANNEL -- not the extreme its label suggests. Re-pick it after a "
        "run if the grids are uninformative; the matrices need no fitting, "
        "so a re-render is seconds against a cached census.",
    )
    parser.add_argument(
        "--out",
        type=str,
        default=None,
        help="markdown file to write (default: <data dir>/reports/phase2.md)",
    )
    args = parser.parse_args(argv)

    name, _, dose = args.headline.partition(":")
    mart = baseline.load()
    frame = baseline.prepare(mart)
    scored, _ = baseline.residuals(frame)
    scored = scored[scored["is_scoreable"]]
    if args.n:
        keep = scored["player_id"].drop_duplicates().head(args.n)
        scored = scored[scored["player_id"].isin(set(keep))]

    cache = Path(args.census) if args.census else None
    if cache is not None and cache.exists():
        census = heldout.read_census(cache, scored)
    else:
        census = heldout.score_all(scored, forest=args.forest, jobs=args.jobs)
        if cache is not None:
            cache.parent.mkdir(parents=True, exist_ok=True)
            heldout.write_census(cache, census, scored)
    path = Path(args.out) if args.out else paths.report_dir() / "phase2.md"
    saved = Path(args.results) if args.results else path.with_suffix(".parquet")
    if saved.exists():
        # Rendering is a pure function of stored results, so a table change
        # costs a re-render rather than a re-analysis.
        # injection_test IS the code that made these, so it must be in the
        # stamp -- the census hash covers baseline+heldout only, and a saved
        # results file would otherwise survive a change to the allocator, a
        # capacity, a mechanism or the ladder and re-render silently stale.
        results = heldout.read_stamped(saved, scored, what="results", extra=(injection_test,))
        print(f"re-rendering from {saved}; analysis skipped")
    else:
        # The coordinated multi-variable injection is part of the condition
        # list, not an extra: it is the case a real manipulator most resembles,
        # and the one where per-DOF truncation matters most, since composing
        # sizes each relabelling against a denominator earlier steps thinned.
        results = injection_test.run(
            scored,
            mart,
            census,
            forest=args.forest,
            design="heldout",
            compositions={"correlated": tuple(injection_test.COMPOSITION_ORDER)},
            seed=args.seed,
            jobs=args.jobs,
        )
        saved.parent.mkdir(parents=True, exist_ok=True)
        heldout.write_stamped(saved, results, scored, extra=(injection_test,))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build(scored, census, results, (name, float(dose))), encoding="utf-8")
    print(f"wrote {path}\nresults at {saved}  (re-render from this; no rerun needed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
