"""Generate dbt doc blocks from the publisher's own field documentation.

The Figshare articles describe every field; those descriptions are captured on
fetch. Committed because dbt needs it without a fetch; regenerating shows a diff
when upstream revises an article, instead of our text going stale.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from fis.data.figshare import DOCS_NAME
from fis.paths import json_dir, project_root

HEADER = """<!-- GENERATED by fis-gen-dbt-docs; edits are lost on the next run.
     Publisher's text, describing the data as published. What our processing
     changes belongs in _models.yml. -->
"""


#: Ends every wyId description; said once on the source instead of six times.
BOILERPLATE = re.compile(r",?\s*assigned by Wyscout\b", re.IGNORECASE)

#: Typos in the published text. Keyed on the exact wording, so an entry stops
#: matching once upstream fixes it and main() reports it as removable.
CORRECTIONS: dict[tuple[str, str], tuple[str, str]] = {
    ("events", "eventName"): ("tteamIdhe name", "the name"),
}


def default_target() -> Path:
    root = project_root()
    if root is None:
        raise RuntimeError("no project checkout found; pass --out explicitly")
    return root / "warehouse" / "models" / "staging" / "_descriptions.md"


def render(docs: dict) -> tuple[str, list[str], list[str]]:
    """Returns the rendered file, corrections applied, and ones no longer needed."""
    out = [HEADER]
    applied, stale = [], []
    for table in sorted(docs):
        entry = docs[table]
        summary = entry.get("summary") or ""
        fields = entry.get("fields") or {}
        if summary:
            out.append(f"{{% docs wyscout_{table} %}}\n{summary}\n{{% enddocs %}}\n")
        for field in sorted(fields):
            text = BOILERPLATE.sub("", fields[field])
            fix = CORRECTIONS.get((table, field))
            if fix:
                wrong, right = fix
                if wrong in text:
                    text = text.replace(wrong, right)
                    applied.append(f"{table}.{field}")
                else:
                    stale.append(f"{table}.{field}")
            text = " ".join(text.split()).rstrip(".;, ") + "."
            out.append(f"{{% docs wyscout_{table}__{field} %}}\n{text}\n{{% enddocs %}}\n")
    return "\n".join(out), applied, stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="fis-gen-dbt-docs", description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=None, help="target .md (default: staging)")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    source = json_dir() / DOCS_NAME
    if not source.exists():
        print(f"error: {source} not found; run fis-fetch-wyscout first", file=sys.stderr)
        return 1

    docs = json.loads(source.read_text())
    target = args.out or default_target()
    rendered, applied, stale = render(docs)
    target.write_text(rendered)

    if not args.quiet:
        tables = sum(1 for t in docs.values() if t.get("summary"))
        fields = sum(len(t.get("fields") or {}) for t in docs.values())
        print(f"Wrote {target}: {tables} table blocks, {fields} field blocks")
        if applied:
            print(f"  corrected upstream typos in: {', '.join(applied)}")
        for name in stale:
            print(f"  note: correction for {name} no longer matches; upstream may have fixed it")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
